### ISSUE TITLE
installing lucky failed

### ISSUE THREAD

**Issue by ChangJoo-Park** [luckyframework/homebrew-lucky#3]
I just brew tab and install lucky. but it failed. how do I do?

==> Installing lucky from luckyframework/lucky
==> Downloading https://github.com/luckyframework/homebrew-lucky/raw/master/tarballs/lucky-0.9.0.tar.gz
Already downloaded: /Users/changjoo-park/Library/Caches/Homebrew/lucky-0.9.0.tar.gz
==> crystal build --release lib/lucky_cli/src/lucky.cr
Last 15 lines from /Users/changjoo-park/Library/Logs/Homebrew/lucky/01.crystal:
2018-02-01 12:34:05 +0900

crystal
build
--release
lib/lucky_cli/src/lucky.cr

Error: File lib/lucky_cli/src/lucky.cr does not exist

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/luckyframework/homebrew-lucky/issues

**Comment by paulcsmith** [comment]
I'm working on a new release process right now actually :) You just happened to try installing now. I'll ping you here when it's all ironed out 👍

**Comment by ChangJoo-Park** [comment]
Thanks Paul :)

**Comment by paulcsmith** [comment]
@ChangJoo-Park No problem! Thanks for giving Lucky a try.

You should be good to go now. You may need to `brew untap luckyframework/homebrew-lucky` and then `brew tap luckyframework/homebrew-lucky`. It may also instruct you to delete an archive because you may have a cached version from when the process wasn't quite finished.

LMK if that works for you :) If you run into any trouble, please post here. This is a brand new process I'm trying out so it may still have some kinks

**Comment by paulcsmith** [comment]
Also note that I need to update the guides. Most things are the same, but there may be some differences. If you have any trouble hop on https://gitter.im/luckyframework/Lobby

I should have guides updated tomorrow

**Comment by ChangJoo-Park** [comment]
I've got "lucky" successfully! 

```
brew untap luckyframework/homebrew-lucky
brew tap luckyframework/homebrew-lucky
```

**Comment by paulcsmith** [comment]
Woo hoo! I’d love to hear what you think once you’ve had a chance to take it for a spin :)
